from typing import Any, Dict, List, Optional, Tuple
from sublime import View, Window, Edit, Buffer, CompletionItem, AutoCompleteFlags

class WindowCommand:
    window: Window
    def run(self, *args: Any, **kwargs: Any) -> None: ...

class TextCommand:
    view: View
    def run(self, edit: Edit, *args: Any, **kwargs: Any) -> None: ...

class EventListener:
    def on_modified(self, view: View) -> None: ...
    def on_selection_modified(self, view: View) -> None: ...
    def on_query_completions(
        self,
        view: View,
        prefix: str,
        locations: List[int]
    ) -> Optional[Tuple[List[CompletionItem], AutoCompleteFlags]]: ...
    def on_init(self, views: List[View]) -> None: ...
    def on_load_project_async(self, window: Window) -> None: ...
    def on_pre_close_project(self, window: Window) -> None: ...
    def on_load_async(self, view: View) -> None: ...
    def on_pre_close(self, view: View) -> None: ...
    def on_post_save_async(self, view: View) -> None: ...
    def on_associate_buffer_async(self, buffer: Buffer) -> None: ...
    def on_window_command(self, window: Window, command_name: str, args: Dict[str, Any]) -> None: ...

