from typing import Any, Callable, Dict, List, Optional, Tuple

# Classes
class Edit:
    pass

class View:
    def substr(self, region: Region) -> str: ...
    def size(self) -> int: ...
    def sel(self) -> Selection: ...
    def window(self) -> Optional[Window]: ...
    def match_selector(self, point: int, selector: str) -> bool: ...
    def expand_to_scope(self, point: int, selector: str) -> Region: ...
    def add_regions(self, key: str, regions: List[Region], scope: str, flags: int = 0) -> None: ...
    def show_popup(self, content: str, flags: int = 0, location: int = -1, max_width: int = 320) -> None: ...
    def erase_regions(self, key: str) -> None: ...
    def add_phantom(self, key: str, region: Region, content: str, layout: int, annotations: Optional[List[str]] = None, flags: int = 0) -> None: ...
    def insert(self, edit: Edit, point: int, text: str) -> None: ...
    def get_regions(self, key: str) -> List[Region]: ...
    def file_name(self) -> Optional[str]: ...
    def id(self) -> int: ...
    def text_point(self, row: int, col: int) -> int: ...
    def viewport_extent(self) -> Tuple[float, float]: ...
    def visible_region(self) -> Region: ...
    def hide_popup(self) -> None: ...
    def word(self, point: int) -> Region: ...
    def set_syntax_file(self, syntax_file: str) -> None: ...
    def run_command(self, command: str, args: Optional[Dict[str, Any]] = None) -> None: ...

class Window:
    def extract_variables(self) -> Dict[str, str]: ...
    def active_view(self) -> Optional[View]: ...
    def focus_view(self, view: View) -> None: ...
    def run_command(self, command: str, args: Optional[Dict[str, Any]] = None) -> None: ...
    def folders(self) -> List[str]: ...
    def views(self) -> List[View]: ...
    def new_file(self, syntax: Optional[str] = None) -> View: ...
    def open_file(self, file_name: str) -> View: ...
    def create_output_panel(self, name: str) -> View: ...

class Buffer:
    pass

class Region:
    def __init__(self, a: int, b: int) -> None: ...
    def begin(self) -> int: ...
    def end(self) -> int: ...

class Selection:
    def add(self, region: Region) -> None: ...
    def clear(self) -> None: ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, index: int) -> Region: ...

class CompletionItem:
    def __init__(
        self,
        trigger: str,
        annotation: str = "",
        completion: str = "",
        completion_format: int = 0,
        kind: int = 0
    ) -> None: ...

# Type aliases
AutoCompleteFlags = int

# Constants
COMPLETION_FORMAT_TEXT: int
KIND_FUNCTION: int
KIND_MARKUP: int
HTML: int

# Functions
def platform() -> str: ...
def packages_path() -> str: ...
def expand_variables(template: str, variables: Dict[str, str]) -> str: ...
def status_message(message: str) -> None: ...
def set_timeout_async(callback: Callable[[], None], delay: int) -> None: ...
def windows() -> List[Window]: ...
def active_window() -> Window: ...

